### ISSUE TITLE
Defining [next|previous]pagetextpatterns (as in example sVimrc) breaks sVimrc

### ISSUE THREAD

**Issue by devnall** [flipxfx/sVim#107]
I copy/pasted the example sVimrc from the README, primarily to blacklist gMail, and couldn't figure out why I still had to go into insert mode in gMail to use the built-in keyboard shortcuts.

I did some digging around and found Issue #24 where @abrookins realized that an unrelated syntax error in sVimrc was causing the blacklists parameter to be ignored.

I went line-by-line through the example sVimrc and narrowed the problem down to the `nextpagetextpatterns` and `prevpagetextpatterns` settings. As far as I can tell, if either of those are called and assigned any values, the entire sVimrc is ignored.

I thought the problem might be with parsing regex so I tried changing the `["Prev(ious)?"]` in the example to `["Prev", "Previous"]`, `["Prev"]`, and just `["P"]` but none seemed to work. I commented out the `prevpagetextpatterns` setting altogether and was still not seeing other settings applied with only the `nextpagetextpatterns` line active. Commenting both textpattern settings out allowed all other settings in the example sVimrc to be honored.

So, two issues, I guess:
1. `nextpagetextpatterns` and `prevpagetextpatterns` settings are either broken or incorrectly documented in the README
2. The example sVimrc in the README doesn't work.

And a bonus third issue (which should probably be broken out into its own feature request?):
It would be nice if, on Save, the sVimrc editor alerted the user to a syntax error that breaks customizations. Currently it behaves the exact same whether the settings are valid and being applied or invalid and not being applied.

MacOS 10.13.6 High Sierra
Safari 12.0 (13606.2.11)
sVim ~1.0.7~ 1.0.6

**Comment by abrookins** [comment]
Huh. That's whack! Thank you for triaging the issue so well. I'll try to check this out soon, though my availability has been spotty. Worse, Apple seems to be employing some crafty tricks to block our submissions to the Extensions Gallery. They keep denying them because "the description is not sufficient," when it's never changed. 🙄

**Comment by isundaylee** [comment]
Hi @devnall, thanks for reporting this! I tried reproducing the issue on 1.0.7, but wasn't able to. 

Just to be sure, are you running version 1.0.7? Since you're on macOS High Sierra, double clicking on the ".safariextz" file would not allow you to actually install it, and would instead prompt you to install version 1.0.6 from the Extensions Gallery. Before 1.0.7 hits the Extensions Gallery, the only way (as far as I know) to install version 1.0.7 is to manually go into Extension Builder in Safari and load the ".safariextz" file (as even by doing it this way, you would need to manually load the 1.0.7 version every time you restart Safari). Did you install 1.0.7 that way?

**Comment by abrookins** [comment]
AFAIK, High Sierra should allow you to install 1.0.7 from the .safariextz
file. Mojave won't, however, and unfortunately, Apple has gone silent about
1.0.7 after repeatedly rejecting it because the plugin description was
never "sufficient." So, we'll see where that goes!

On High Sierra, manually loading the plugin from Extension Builder used to
be necessary because the plugin wasn't properly signed with a developer
certificate. For the past year or so, they have been signed, so I expect
installing from the file should work fine. Someone let me know if I'm wrong
-- I'm on Mojave now!

**Comment by isundaylee** [comment]
Hi @devnall, the go-to-next-page/go-to-prev-page feature is a new feature in 1.0.7. Therefore the *pagetextpatterns settings did not exist in the 1.0.6 version. And that might explain the parsing failure. 

I agree that at this point we might wanna change the README back until 1.0.7 gets through review. But that would be @abrookins 's call.

**Comment by abrookins** [comment]
Regarding no 1.0.7 direct install on High Sierra: Argh! Apple must have
released Safari 12 for High Sierra. :(

The README with those settings is for version 1.0.7. However, given that
our settings parser must die if it sees an unknown setting (just a guess),
it makes sense to comment those lines out with a warning to only uncomment
them if using 1.0.7 or higher. I'd take a PR for that!

--Andrew

**Comment by devnall** [comment]
Yep, Safari 12 on High Sierra is a thing.

Added a note to the README for anyone else who runs into this issue in the above PR. Thanks to both of you for the quick responses and assistance. Good luck getting sVim through the approval process!

**Comment by abrookins** [comment]
Apple appears to have accepted 1.0.7, though you won't know if you have it because the app store still reports it as 1.0.6. 😦 That complicates the README fix.

**Comment by devnall** [comment]
>  I'm inclined to do nothing, because the only people who would be affected now are people who manually installed the extension and are still using the last version of Safari -- probably not many people?

I agree, 1.0.7 getting accepted makes this a real edge case and this thread is probably sufficient documentation on the outside chance that someone else bumps into this problem. I'll close both the PR and this issue.

Thanks for jumping through the requisite hoops to get the new release into the Extension Gallery!
