### ISSUE TITLE
mapping to "z" does not work

### ISSUE THREAD

**Issue by nikitavoloboev** [flipxfx/sVim#48]
For example if I had this line in the sVimrc `map "z" goToInput`, it does not work. Only if I press z two times, will it work.

**Comment by luchenyuxx** [comment]
By default, mapping "z i" -> zoom in, "z o" -> zoom out, etc, is set. So mapping only "z" will confuse sVim.

**Comment by nikitavoloboev** [comment]
Can you change these default mappings anywhere? I wish to make a standalone `z` mapping.

**Comment by luchenyuxx** [comment]
Yes, you can. Try to remap these functions.

Key | Description | Function
----|-------------|---------
"z i" | zoom page in | zoomPageIn 
"z o" | zoom page out | zoomPageOut 
"z 0" | zoom page to original size | zoomOrig

**Comment by nikitavoloboev** [comment]
Hey @luchenyuxx 

I have these mappings in my sVimc:

```Bash
map "v" goToInput
map "c" lastClosedTab
map "q" zoomPageIn
map "u" zoomPageOrig
map "m" zoomPageOut
map "o" zoomPageIn
map "e" quit
map "d" createHint
map "f" createTabbedHint
map "z" quit
```

The "z" mapping does not work. Shouldn't it remap my z binding since I already mapped all the default z bindings?

**Comment by luchenyuxx** [comment]
Whoops, it turns out my suggestion doesn't work.
sVim allows multiple bindings to the same function. So although we mapped new keys to the function, the default ones are still loaded.
A solution may be to have a new keyword "unmap" to unmap default binding.
However, I found that in vim, 'z' and 'g' are default prefixes that you can not change. To respect vim, I think maybe it's a good idea to keep 'z' and 'g' as prefixes.
Just my opinions.

**Comment by luchenyuxx** [comment]
It turns out my suggestion doesn't work.
I will make sVim more clever to ignore longer sequence if shorter one is set.

**Comment by luchenyuxx** [comment]
You can do this:
```
unmap "z i"
unmap "z o"
unmap "z 0"
map "z" quit
```

**Comment by nikitavoloboev** [comment]
This works. Thank you @luchenyuxx
